### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './script//ssc_path.ssc'

### ISSUE THREAD

**Issue by sugizo** [beltoforion/stellarium-to-video#20]
**env**
wsl debian (windows subsidiary linux)

**execute**
```
python3 /mnt/c/stellarium-to-video/stellarium-to-video.py \
-ts P6M -dt P1D -o "/mnt/c/Users/sugizo/Downloads/vertical.mp4" \
-t /mnt/c/stellarium-to-video/script/planet_track.ssc \
-sz 1080x1920 -wsz 1080x1920 \
-v 180,30,70 \
-d 1961-10-08T12:00:00+01:00 \
-l Freiberg -c "Dance of Planets"
```

**result**
```
Traceback (most recent call last):
  File "/mnt/c/stellarium-to-video/stellarium-to-video.py", line 486, in <module>
    main()
  File "/mnt/c/stellarium-to-video/stellarium-to-video.py", line 479, in main
    sa.create_script(script_folder)
  File "/mnt/c/stellarium-to-video/stellarium-to-video.py", line 184, in create_script
    with open(f'./script/{self.__param.template}', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './script//mnt/c/stellarium-to-video/script/planet_track.ssc'
```

**solution**
**change**
```
        with open(f'./script/{self.__param.template}', 'r') as file:
            script = file.read()
```
**into (remove ./script )**
```
        with open(f'{self.__param.template}', 'r') as file:
            script = file.read()
```

thanks and best regards

**Comment by sugizo** [comment]
not sure bout this situation yet, since try without -t parameter it backfire the shell command
**e.g.**
```
cd
python3 /mnt/c/stellarium-to-video/stellarium-to-video.py \
-ts PT2H -dt PT1M -o /mnt/c/Users/sugizo/Downloads/berlin.mp4 \
-v 90,25,70 \
-d 2024-09-25 \
-l Berlin -c "The Sky over Berlin"
```

**result**
```
Warning: No time given. The script will try to use the sunset time of the given day!
Traceback (most recent call last):
  File "/mnt/c/Cloud/MEGA/Git/python/stellarium-to-video/stellarium-to-video.py", line 486, in <module>
    main()
  File "/mnt/c/Cloud/MEGA/Git/python/stellarium-to-video/stellarium-to-video.py", line 479, in main
    sa.create_script(script_folder)
  File "/mnt/c/Cloud/MEGA/Git/python/stellarium-to-video/stellarium-to-video.py", line 184, in create_script
    with open(f'{self.__param.template}', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'default.ssc'
```

**solution must change directory to script first then execute the shell**
```
cd /mnt/c/stellarium-to-video/script
python3 /mnt/c/stellarium-to-video/stellarium-to-video.py \
-ts PT2H -dt PT1M -o /mnt/c/Users/sugizo/Downloads/berlin.mp4 \
-v 90,25,70 \
-d 2024-09-25 \
-l Berlin -c "The Sky over Berlin"
```

best regards

**Comment by sugizo** [comment]
**suggestion**
perhaps just use 
the if condition to check 
```
if without -t parameter :
    then use __script like on previous kalstar.py 
```

**e.g. on modified kalstar.py**
```
    x_label = random.randint(50, 99)

    list_color = ["'#FFFFE0'", "'#FAFAD2'", "'#FFA07A'", "'#F08080'", 
                  "'#FFB6C1'", "'#90EE90'", "'#D3D3D3'", "'#778899'", 
                  "'#E0FFFF'", "'#20B2AA'", "'#B0C4DE'", "'#ADD8E6'", 
                  "'#87CEFA'", 
                 ]

    color_caption = random.choice(list_color)
    color_date = random.choice(list_color)

    miklyway_intensity = random.randint(0, 2)

    line_thickness = random.randint(1, 3)

    list_art_intensity = [0, .1, .2]

    art_intensity = random.choice(list_art_intensity)

    zodiacal_light_intensity = random.randint(0, 2)

    __script = """

// Author: Ingo Berg
// Version: 1.0
// License: Public Domain
// Name: Kaleidoskop Sternenhimmel
// Description: Berechnung des Sternenhimmels

param_frame_folder = "$FRAME_FOLDER$"
param_az = $AZ$
param_alt = $ALT$
param_lat = $LAT$
param_long = $LONG$
param_title = "$TITLE$"
param_date = "$DATE$"
param_timespan = $TIMESPAN$
param_fov = $FOV$
param_dt=$DELTAT$

function makeVideo(date, file_prefix, caption, hours, long, lat, alt, azi)
{
    core.setDate(date, "utc");
    core.setObserverLocation(long, lat, 425, 1, "", %s);
    core.wait(0.5);

    core.moveToAltAzi(alt, azi)
    core.wait(0.5);

    label = LabelMgr.labelScreen(caption, %s, 30, false, 38, %s);
    LabelMgr.setLabelShow(label, true);

    labelTime = LabelMgr.labelScreen("", %s, 90, false, 26, %s);
    LabelMgr.setLabelShow(labelTime, true);

    core.wait(0.5);

    max_sec = hours * 60 * 60
    for (var sec = 0; sec < max_sec; sec += param_dt) {
        core.setDate('+' + param_dt + ' seconds');
        LabelMgr.setLabelText(labelTime, core.getDate(""));
        core.wait(0.1);
        core.screenshot(file_prefix);
    }

    LabelMgr.deleteAllLabels();
}

core.setTimeRate(0); 
core.setGuiVisible(false);

AsterismMgr.setFlagLabels(true);
AsterismMgr.setFlagLines(true);
AsterismMgr.setAsterismLineThickness(%s);

MilkyWay.setFlagShow(true);
MilkyWay.setIntensity(%s);

SolarSystem.setFlagPlanets(true);
SolarSystem.setFlagLabels(true);

StelSkyDrawer.setFlagTwinkle(true);
StelSkyDrawer.setFlagForcedTwinkle(true);

StarMgr.setFlagStars(true);
StarMgr.setFlagLabels(true);

ConstellationMgr.setFlagLabels(true);
ConstellationMgr.setFlagArt(true);
ConstellationMgr.setArtIntensity(%s);
ConstellationMgr.setFlagLines(true);
ConstellationMgr.setConstellationLineThickness(%s);
ConstellationMgr.setFlagBoundaries(false);

LandscapeMgr.setFlagLandscape(false);
LandscapeMgr.setFlagAtmosphere(false);

ZodiacalLight.setFlagShow(true);
ZodiacalLight.setIntensity(%s);

StelMovementMgr.zoomTo(param_fov, 0);
core.wait(0.5);

makeVideo(param_date, "frame_", param_title, param_timespan, param_long, param_lat, param_alt, param_az)
core.screenshot("final", invert=false, dir=param_frame_folder, overwrite=true);
core.setGuiVisible(true);
core.quitStellarium();

    """ % (observer_location, x_label, color_caption, x_label, color_date, 
           line_thickness, miklyway_intensity, art_intensity, line_thickness, 
           zodiacal_light_intensity)
```


best regards

**Comment by beltoforion** [comment]
fixed; the script folder is now always searched in the folder where stellarium-to-video.py resides
